### ISSUE TITLE
Java 8 Date/Time migration

### ISSUE THREAD

**Issue by jatsqi** [Vaultionizer/vault-server#20]
We should migrate from the old java.sql types to the more recent ones. 

In this example, we could replace the old Timestamp with the `Instant` type.
https://github.com/Vaultionizer/vault-server/blob/5bbb01b3617fb95f06cc926bba4982780d5c7da5/src/main/java/com/vaultionizer/vaultserver/model/db/RefFilesModel.java#L25

**Comment by keksklauer4** [comment]
Done.
