### ISSUE TITLE
Possible inconsistency with GenericAuthDto

### ISSUE THREAD

**Issue by jatsqi** [Vaultionizer/vault-server#21]
We should stick to one pattern when it comes to authentication data.
In this example the AuthDto is not wrapped inside an auth JSON object which a user might expect.
https://github.com/Vaultionizer/vault-server/blob/5bbb01b3617fb95f06cc926bba4982780d5c7da5/src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java#L47

**Comment by keksklauer4** [comment]
Done.
